//https://staxmanade.com/CssToReact/
export default {
    "MsOverflowStyle": "scrollbar",
    "WebkitFontSmoothing": "antialiased",
    "sePrimaryColor": "#3dcd58",
    "sePrimaryColorRgb": "61,205,88",
    "sePrimaryColor1": "#f0fff0",
    "sePrimaryColor2": "#f0fff0",
    "sePrimaryColor3": "#bdf2c1",
    "sePrimaryColor4": "#8ee698",
    "sePrimaryColor5": "#64d975",
    "sePrimaryColor6": "#3dcd58",
    "sePrimaryColor7": "#29a644",
    "sePrimaryColor8": "#198033",
    "sePrimaryColor9": "#0d5923",
    "sePrimaryColor10": "#073315",
    "seMagenta": "#eb2f96",
    "sePink": "#eb2f96",
    "seRed": "#ff4d4f",
    "seVolcano": "#fa541c",
    "seOrange": "#fa8c16",
    "seYellow": "#fadb14",
    "seGold": "#faad14",
    "seCyan": "#13c2c2",
    "seLime": "#a0d911",
    "seGreen": "#3dcd58",
    "seBlue": "#1890ff",
    "seGeekblue": "#2f54eb",
    "sePurple": "#722ed1",
    "seSuccessColor": "#3dcd58",
    "seWarningColor": "#faad14",
    "seErrorColor": "#ff4d4f",
    "seDisabledColor": "rgba(0, 0, 0, 0.25)",
    "seDisabledBg": "rgba(0, 0, 0, 0.04)",
    "seLinkColor": "#3dcd58",
    "seHoverColor": "#64d975",
    "seHoverBg": "rgba(0, 0, 0, 0.02)",
    "seFontSizeSm": "12px",
    "seFontSizeLg": "16px",
    "seColor": "rgba(0, 0, 0, 0.65)",
    "seColorLg": "rgba(0, 0, 0, 0.88)",
    "seColorSm": "rgba(0, 0, 0, 0.45)",
    "seColorXs": "rgba(0, 0, 0, 0.25)",
    "seColorInverse": "#FFFFFF",
    "sePadding": "16px",
    "sePaddingSm": "12px",
    "sePaddingXs": "8px",
    "sePaddingLg": "24px",
    "seHeight": "36px",
    "seHeightSm": "28px",
    "seHeightLg": "48px",
    "seBgColor": "#F4F6F8",
    "seContentBg": "#FFFFFF",
    "seBorderColor": "#D9D9D9",
    "seHeaderColor": "rgba(0, 0, 0, 0.88)",
    "seHeaderBg": "#FFFFFF",
    "seShadowColor": "rgba(0, 0, 0, 0.1)",
    "seTheme": "light",
    "seStyle": "light",
    "seBrandBg": "#f0fff0",
    "seBrandBorder": "#8ee698",
    "seBrandHoverd": "#64d975",
    "seBrandActive": "#29a644",
    "seBrandNomarl": "#3dcd58",
    "seBgLayout": "#F4F6F8",
    "seBgContainer": "#FFFFFF",
    "seBgContainerSecondary": "#f8f9fb",
    "seBgElevated": "#FFFFFF",
    "seBgSpotlight": "rgba(0, 0, 0, 0.85)",
    "seTextTitle": "rgba(0, 0, 0, 0.88)",
    "seTextPrimary": "rgba(0, 0, 0, 0.65)",
    "seTextSecondary": "rgba(0, 0, 0, 0.45)",
    "seTextDisabled": "rgba(0, 0, 0, 0.25)",
    "seTextInverse": "#FFFFFF",
    "seFontSizeH0": "46px",
    "seFontSizeH1": "38px",
    "seFontSizeH2": "30px",
    "seFontSizeH3": "24px",
    "seFontSizeH4": "20px",
    "seFontSizeH5": "16px",
    "seFontSize": "14px",
    "seFontSizeFootnote": "12px",
    "seLineHeightH0": "54px",
    "seLineHeightH1": "46px",
    "seLineHeightH2": "38px",
    "seLineHeightH3": "32px",
    "seLineHeightH4": "28px",
    "seLineHeightH5": "24px",
    "seLineHeight": "22px",
    "seLineHeightFootnote": "20px",
    "seFill3": "rgba(0, 0, 0, 0.04)",
    "seFill4": "rgba(0, 0, 0, 0.02)",
    "seBorderBase": "#D9D9D9",
    "seBorderSplit": "#F0F0F0",
    "seBorderRadius": "4px",
    "seBorderRadiusMd": "8px",
    "seBorderRadiusLg": "16px",
    "seShadowBox": "0 2px 14px rgba(0, 0, 0, 0.03)",
    "seShadowHeader": "0 1px 8px rgba(0, 0, 0, 0.06)",
    "seShadowNav": "4px 0px 6px 0px rgba(0, 0, 0, 0.04)",
    "seInfoNormal": "#1890ff",
    "seInfoBorder": "#91d5ff",
    "seInfoBg": "#e6f7ff",
    "seSuccessNormal": "#3dcd58",
    "seSuccessBorder": "#8ee698",
    "seSuccessBg": "#f0fff0",
    "seWarningNormal": "#faad14",
    "seWarningBorder": "#ffe58f",
    "seWarningBg": "#fffbe6",
    "seErrorNormal": "#ff4d4f",
    "seErrorBorder": "#ffccc7",
    "seErrorBg": "#fff2f0",
    "seOthersGreenHeavy": "#198033",
    "seOthersGreen": "#3dcd58",
    "seOthersGreenLight": "#8ee698",
    "seOthersGreenBg": "#f0fff0",
    "seOthersGold": "#faad14",
    "seOthersGoldLight": "#ffe58f",
    "seOthersGoldBg": "#fffbe6",
    "seOthersRed": "#ff4d4f",
    "seOthersRedLight": "#ffccc7",
    "seOthersRedBg": "#fff2f0",
    "seOthersBlue": "#1890ff",
    "seOthersBlueLight": "#91d5ff",
    "seOthersBlueBg": "#e6f7ff",
    "seOthersMagenta": "#eb2f96",
    "seOthersMagentaLight": "#ffadd2",
    "seOthersMagentaBg": "#fff0f6",
    "seOthersViolet": "#5A3FFF",
    "seOthersVioletLight": "#cabaff",
    "seOthersVioletBg": "#f4f0ff",
    "seOthersPurple": "#9254de",
    "seOthersPurpleLight": "#d3adf7",
    "seOthersPurpleBg": "#f9f0ff",
    "seOthersCyan": "#13c2c2",
    "seOthersCyanLight": "#87e8de",
    "seOthersCyanBg": "#e6fffb",
    "seOthersStoneblue": "#65789B",
    "seOthersStoneblueLight": "#b6bbc2",
    "seOthersStoneblueBg": "#ced5db",
    "seOthersGeekblue": "#597ef7",
    "seOthersGeekblueLight": "#adc6ff",
    "seOthersGeekblueBg": "#f0f5ff",
    "seScreenMd": "768px",
    "seScreenSm": "576px",
    "seScreenXs": "480px",
    "seScreenLg": "992px",
    "seScreenXl": "1200px",
    "seScreenXxl": "1600px"
}
