
let taskTypes = [
  '中压柜',
  '低压柜',
  '变压器',
  '母线系统',
  '敏感及重要设备',
  '系统运行环境与工况',
  '电容补偿柜状态',
  '保护定值',
  '配电监控系统',
]
export default {
  MiddleVoltagePanelInfo:{
    title:'中压柜',
    subTitle:'中高压柜快速巡检',
    subTasks:{
      Frequency:{
        title:'维护频率',
        options:[
          {title:'半年',value:1},
          {title:'一年',value:2},
          {title:'其他',value:3},
          {title:'从不',value:4},
        ]
      },
      BackupItemRatio:{
        title:'备件比例',
        options:[
          {title:'≤10%',value:1},
{title:'>10%',value:2},
{title:'无备件',value:3},
        ]
      },
      MaintenanceTeam:{
        title:'维护团队',
        options:[
          {title:'内部',value:1},
          {title:'外包',value:2},
          {title:'原厂',value:3},
        ]
      },
      IsDoElectricalFixed:{
        title:'是否做过电气紧固',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoBreakerOperationExperiment:{
        title:'是否做过断路器操作试验',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoRust:{
        title:'柜体机构无锈蚀现象',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoProtectExperiment:{
        title:'是否做过保护传跳试验',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoPressureTest:{
        title:'是否做过耐压测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoBreakerPropertiesExperiment:{
        title:'是否做过断路器特性试验',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsHaveBreakerLubricationOperation:{
        title:'是否有断路器机构润滑操作',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      }
    }
  },
  LowVoltagePanelInfo:{
    title:'低压柜',
    subTitle:'低压柜快速巡检',
    subTasks:{
      Frequency:{
        title:'维护频率',
        options:[
          {title:'半年',value:1},
          {title:'一年',value:2},
          {title:'其他',value:3},
          {title:'从不',value:4},
        ]
      },
      BackupItemRatio:{
        title:'备件比例',
        options:[
          {title:'≤10%',value:1},
{title:'>10%',value:2},
{title:'无备件',value:3},
        ]
      },
      MaintenanceTeam:{
        title:'维护团队',
        options:[
          {title:'内部',value:1},
          {title:'外包',value:2},
          {title:'原厂',value:3},
        ]
      },
      IsNoCleaned:{
        title:'柜内无积尘、异物',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoHealthyParts:{
        title:'柜内无“带病”运行元器件',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoElectricalFixed:{
        title:'是否做过电气紧固',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoBreakerOperationExperiment:{
        title:'是否做过断路器操作试验',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoRust:{
        title:'柜体机构无锈蚀现象',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoInsulatedTest:{
        title:'是否做过绝缘测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoTouchedTest:{
        title:'是否做过触头接触电阻测试项目',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoBreakerPropertiesExperiment:{
        title:'是否做过断路器特性试验',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
    }
  },
  TransformerInfo:{
    title:'变压器',
    subTitle:'变压器快速巡检',
    subTasks:{
      Frequency:{
        title:'维护频率',
        options:[
          {title:'半年',value:1},
          {title:'一年',value:2},
          {title:'其他',value:3},
          {title:'从不',value:4},
        ]
      },
      BackupItemRatio:{
        title:'备件比例',
        options:[
          {title:'≤10%',value:1},
{title:'>10%',value:2},
{title:'无备件',value:3},
        ]
      },
      MaintenanceTeam:{
        title:'维护团队',
        options:[
          {title:'内部',value:1},
          {title:'外包',value:2},
          {title:'原厂',value:3},
        ]
      },
      IsNoCleaned:{
        title:'柜内无积尘、异物',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoSensorInLocation:{
        title:'无温度传感器未放到位的现象',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoException:{
        title:'无绝缘子异常现象',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoBlowerTest:{
        title:'是否做过风机测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoTemperatureTest:{
        title:'是否做过温控器测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoResistanceTest:{
        title:'是否做过绕组直阻测量',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoInsulatedTest:{
        title:'是否做过绕组绝缘测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoPressureTest:{
        title:'是否做过耐压测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
    }
  },
  BusSystemInfo:{
    title:'母线系统',
    subTitle:'母线系统',
    subTasks:{
      Frequency:{
        title:'维护频率',
        options:[
          {title:'半年',value:1},
          {title:'一年',value:2},
          {title:'偶尔',value:3},
          {title:'从不',value:4},
        ]
      },
      BackupItemRatio:{
        title:'备件比例',
        options:[
          {title:'备件不足',value:1},
{title:'备件充足',value:2},
{title:'无备件',value:3},
        ]
      },
      MaintenanceTeam:{
        title:'维护团队',
        options:[
          {title:'内部',value:1},
          {title:'外包',value:2},
          {title:'原厂',value:3},
        ]
      },
    }
  },
  SensitiveAndImportantDeviceInfo:{
    title:'敏感及重要设备',
    subTasks:{
      Frequency:{
        title:'维护频率',
        options:[
          {title:'半年',value:1},
          {title:'一年',value:2},
          {title:'其他',value:3},
          {title:'从不',value:4},
        ]
      },
      BackupItemRatio:{
        title:'备件比例',
        options:[
          {title:'≤10%',value:1},
{title:'>10%',value:2},
{title:'无备件',value:3},
        ]
      },
      MaintenanceTeam:{
        title:'维护团队',
        options:[
          {title:'内部',value:1},
          {title:'外包',value:2},
          {title:'原厂',value:3},
        ]
      },
      IsNoCleaned:{
        title:'柜内无积尘、异物',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsNoHealthyParts:{
        title:'柜内无“带病”运行元器件',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoPowerControllerTest:{
        title:'是否做过功率因素控制器功能测试',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsHaveLeaveAppearance:{
        title:'电容是否有鼓包漏液现象',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoVolumeTest:{
        title:'是否做过电容容值测量',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
      IsDoDeviceMaintenance:{
        title:'是否做过电容柜的通风系统及滤尘装置维护',
        options:[
          {title:'否',value:0},
          {title:'是',value:1},
        ]
      },
    }
  },
  RunningEnvironmentInfo:{
    title:'系统运行环境与工况',
    subTitle:'系统运行环境与工况',
  },
  CapacitorOffsetInfo:{
    title:'电容补偿柜状态',
    subTitle:'电容补偿柜状态',
  },
  ConstantValueInfo:{
    title:'保护定值'
  },
  ControlSystemInfo:{
    title:'配电监控系统',
    subTitle:'配电监控系统',
  },
}
