export default {
  lang_loading_waiting: 'Loading, please wait...',
  lang_clear_filter: 'Clear Filter Condition',
  lang_empty_data: 'No Data',
  lang_ticket_list_no_permission: 'You have no authorization to operate, please contact the administrator',
  lang_load_more: 'Loading, please wait...',

  lang_status_1: 'To Do',
  lang_status_2: 'In Progress',
  lang_status_3: 'Submitted',
  lang_status_4: 'Reverted',
  lang_status_5: 'Completed',
  lang_status_6: 'Ignored',

  lang_single_select_search_no_result: 'No results found',
  lang_single_select_manual_input: 'Manual Entry',
  lang_single_select_input_keyword: 'Enter Keywords',

  lang_tabbar_asset: 'Assets',
  lang_tabbar_ticket: 'Tickets',
  lang_tabbar_alarm: 'Alarms',
  lang_tabbar_profile: 'Mine',

  lang_asset_tab: 'Assets',
  lang_asset_tab_ledger: 'Ledger',
  lang_asset_tab_inventory: 'Inventory',

  lang_asset_invalid_qrcode: 'Not a recognizable QR code',
  lang_asset_identify_fail: 'Recognition Failure',
  lang_asset_alert_know: 'Confirm',
  lang_asset_search_tip: 'Please search device name/code',
  lang_asset_search_asset_tip: 'Please search asset name',
  lang_asset_status: 'Asset Status',
  lang_asset_status_using: 'In Use',
  lang_asset_status_stop: 'Stopped',
  lang_asset_status_repairing: 'Under Repair',
  lang_asset_status_idle: 'Idle',
  lang_asset_status_transfer: 'In Allocation',
  lang_asset_status_normal: 'Normal',
  lang_asset_status_illness: 'Defected',
  lang_asset_status_standby: 'Standby',
  lang_asset_status_breakdown: 'Fault',
  lang_asset_status_offline: 'Offline',
  lang_asset_image_loading_exception: 'Image loading failure!',


  lang_asset_device_info: 'Device Info',
  lang_asset_realtime_data: 'Realtime Data',
  lang_asset_basic_info: 'Basic Info',
  lang_asset_parameters: 'Device Parameters',
  lang_asset_file: 'Device File',
  lang_asset_name: 'Device Name',
  lang_asset_code: 'Device Code',
  lang_asset_location: 'Location',
  lang_asset_inventory: 'Inventory Record',
  lang_asset_tickets: 'Maintenance Record',

  lang_alarm_tab: 'Alarms',
  lang_alarm_type_bu: 'Operation Alarm',
  lang_alarm_type_comm: 'Communication Alarm',

  lang_alarm_filter: 'Filter',
  lang_alarm_filter_level: 'Level',
  lang_alarm_filter_type: 'Type',
  lang_alarm_filter_time: 'Time',

  lang_alarm_filter_type_tx1: 'Device Offline',
  lang_alarm_filter_type_tx2: 'Gateway Offline',
  lang_alarm_filter_type_tx3: 'Agent Offline',
  lang_alarm_filter_type_tx4: 'Local System Offline',
  lang_alarm_filter_level_h: 'High',
  lang_alarm_filter_level_m: 'Medium',
  lang_alarm_filter_level_l: 'Low',
  lang_alarm_filter_reset: 'Reset',
  lang_alarm_filter_start_time: 'Start Time',
  lang_alarm_filter_end_time: 'End Time',
  lang_alarm_time_picker_title: 'Select Date',
  lang_alarm_time_picker_ok: 'Confirm',
  lang_alarm_time_picker_resolve: 'Resolve',
  lang_alarm_time_picker_cancel: 'Cancel',
  lang_alarm_time_picker_invalid_lip: 'Start time cannot be late than end time',

  lang_alarm_tip1: 'Alram Deactivated',
  lang_alarm_tip2: 'Alarm may have been deactivated automatically or by other users.',
  lang_alarm_tip3: 'Deactive the alarm?',
  lang_alarm_device: 'Device',

  lang_alarm_level_h: 'H',
  lang_alarm_level_m: 'M',
  lang_alarm_level_l: 'L',
  lang_alarm_detail: 'Details',
  lang_alarm_list_undone: 'Active',
  lang_alarm_list_done: 'Inactive',
  lang_alarm_action_create_ticket: 'Create Ticket',
  lang_alarm_action_inspect_ticket: 'View Ticket',
  lang_alarm_action_relieve: 'Deactive',
  lang_alarm_relieve_info: 'Deactive the alarm manually',
  lang_alarm_relieve_info2: 'Data is normal and the alarm is deactived automatically.',
  lang_alarm_relieve_info3: 'Deactive Manually',

  lang_alarm_alert_info: 'The device is not on the hierarchy tree or no permission.',

  lang_alarm_info_step: 'Alarm Occurs',
  lang_alarm_info_device: 'Device',
  lang_alarm_info_set_value: 'Set Value',
  lang_alarm_info_location: 'Location',
  lang_alarm_info_duration: 'Duration',
  lang_alarm_info_gateway: 'Gateway',
  lang_alarm_info_create_time: 'Time',

  lang_alarm_time_format_year: 'y',
  lang_alarm_time_format_month: 'm',
  lang_alarm_time_format_day: 'd',
  lang_alarm_time_format_hour: 'h',
  lang_alarm_time_format_minute: 'm',
  lang_alarm_time_format_second: 's',

  lang_profile_new_version: 'New Version Found',
  lang_profile_action_update: 'Update',
  lang_profile_my: 'Profile',
  lang_profile_logout: 'Logout',
  lang_profile_alert_logout: 'Logout',
  lang_profile_alert_info: 'Logout this account?',
  lang_profile_no_download_config: 'No APP download link. Please contact your administrator.',
  lang_profile_account: 'Staff Number',
  lang_profile_display_name: 'Display Name',
  lang_profile_my_partner: 'My Tenants',
  lang_profile_version: 'Version',
  lang_profile_alert_done: 'Done',
  lang_profile_updated: 'This is the latest version.',
  lang_profile_alert_do_update: 'Update',
  lang_profile_new_version_tip: 'Please update to EnergyHub V${0}!',

  lang_host_config_network_invalid: 'Validation failed. Please check mobile network and server address',
  lang_host_input_server_hint: 'Please input server address',
  lang_host_server_config: 'Server address setting',
  lang_host_server_example: 'Please input server address with such format：http://192.168.1.1:8080 ',
  lang_host_config_done: 'Completed',

  lang_login_title: 'User Login',
  lang_login_user_hint: 'Input your account',
  lang_login_password_hint: 'Input your password',
  lang_login_button: 'Login',
  lang_login_remember: 'Save account for next login',
  lang_login_help: 'For login problems please contat 010—8888 8888',
  lang_login_server_config: 'Server address setting>',

  lang_create_alarm_ticket_title: 'Create Alarm Ticket',
  lang_create_alarm_ticket_asset_range: 'Asset Range',
  lang_create_alarm_ticket_system_category: 'System Category',
  lang_create_alarm_ticket_system_category_title: 'Please select system category',
  lang_ticket_all_categories: ['Air Conditioning', 'Heat', 'Lightning', 'Office', 'Elevator', 'Transformer & Distribution', 'Data Room', 'Production', 'Water Treatment', 'Compressed Aire', 'Water Supply & Drainage', 'Others', 'Environment Parameters',],
  lang_create_alarm_ticket_executor: 'Executor',
  lang_create_alarm_ticket_customer: 'Customer',
  lang_create_alarm_ticket_Save: 'Save',
  lang_create_alarm_ticket_select_executor: 'Please select executor',
  lang_create_alarm_ticket_select: 'Please select',

  lang_unknown_error: 'Unknown Error',
  lang_network_error: 'Failed to load, please check your network setting',
  lang_cookie_invalid: 'Failed to login, please login again',
  lang_permission_expired: 'Permissions have expired',
  lang_account_deleted: 'Account has been deleted, please contact your administrator',
  lang_server_error: 'The system is being upgraded and will be back soon',
  lang_exit_app: 'Press again to exit the app',
  lang_camera_permission: 'Allow this App to access camera in the "Settings" of your phone',
  lang_scan_page_light: 'Light',
  lang_scan_page_light_on: 'On',
  lang_scan_page_light_off: 'Off',

  lang_login_error_not_exist_account: 'Username not registered in the system',
  lang_login_error_invalid_account: 'Wrong Username Or Password',

  lang_toolbar_ok: 'Done',
  lang_toolbar_submit: 'Submit',

  lang_image_picker_cancel: 'Cancel',
  lang_image_picker_accept: 'Allow',
  lang_image_picker_accept_msg: 'Please allow this App to get access your camera in your phone\'s "Settings"',
  lang_image_picker_access_storage: 'Please allow this App to get read and write your storage in your phone\'s "Settings"',
  lang_image_picker_open_photos: 'Open the Camera',
  lang_image_picker_from_photos: 'Get it from your photo album',
  lang_image_picker_title: 'Photo',
  lang_image_picker_access_photos: 'Please allow this App to get access your photos in your phone\'s "Settings"',
  lang_image_picker_read_storage: 'Please allow this App to access your storage in your phone\'s "Settings"',
  lang_image_picker_no_photos: 'No Photos',
  lang_image_take_photo: 'Take Photos',

  lang_offline_view_tip: 'Network connection failed. Click to retry.',
  lang_ticket_select_site: 'Please select a site',
  lang_ticket_title_create: 'Create Ticket',
  lang_ticket_title_edit: 'Edit Ticket',
  lang_ticket_valid_select_assets: 'Please select asset range',
  lang_ticket_valid_select_time: 'Please input time estimate',
  lang_ticket_valid_title: 'Please input ticket name',
  lang_ticket_valid_content: 'Please input description',
  lang_ticket_valid_use_time: 'Please input time estimate',
  lang_ticket_valid_use_time_format: 'Invalid time estimate',
  lang_ticket_create_start_time: 'Suggested Time',
  lang_ticket_create_duration: 'Time Estimate',
  lang_ticket_create_duration_hint: 'Please input',
  lang_ticket_create_duration_units: ['Hour', 'Day'],
  lang_ticket_create_success_tip: 'Ticket created',
  lang_ticket_delete_tip: 'Delete this ticket?',

  lang_ticket_edit_title_tip: 'Maximum 30 characters for the title.',
  lang_ticket_edit_title_tip2: 'Please input ticket name.',
  lang_ticket_edit_content_tip: 'Please input ticket description.',

  lang_select_partners: 'Select tenants',
};
