export default {
  lang_loading_waiting: '加载中，请稍候...',
  lang_clear_filter: '清空筛选条件',
  lang_empty_data: '暂无数据',
  lang_ticket_list_no_permission: '您没有这一项的操作权限，请联系系统管理员',
  lang_load_more: '加载中，请稍后...',

  lang_status_1: '待执行',
  lang_status_2: '执行中',
  lang_status_3: '待审批',
  lang_status_4: '已驳回',
  lang_status_5: '已完成',
  lang_status_6: '已忽略',

  lang_single_select_search_no_result: '搜索无结果',
  lang_single_select_manual_input: '手动输入',
  lang_single_select_input_keyword: '输入关键字',

  lang_tabbar_asset: '资产管理',
  lang_tabbar_ticket: '运维工单',
  lang_tabbar_alarm: '报警管理',
  lang_tabbar_profile: '个人中心',

  lang_asset_tab: '资产管理',
  lang_asset_tab_ledger: '台账',
  lang_asset_tab_inventory: '盘点',

  lang_asset_invalid_qrcode: '非系统可识别的二维码',
  lang_asset_identify_fail: '识别失败',
  lang_asset_alert_know: '知道了',
  lang_asset_search_tip: '请搜索设备名称/编号',
  lang_asset_search_asset_tip: '请搜索资产名称',
  lang_asset_status: '资产状态',
  lang_asset_status_stop: '已停运',
  lang_asset_status_using: '在用',
  lang_asset_status_repairing: '维修中',
  lang_asset_status_idle: '闲置',
  lang_asset_status_transfer: '调拨中',
  lang_asset_status_normal: '正常',
  lang_asset_status_illness: '带病运行',
  lang_asset_status_standby: '备机',
  lang_asset_status_breakdown: '故障',
  lang_asset_status_offline: '未上线',
  lang_asset_image_loading_exception: '图片加载异常!',

  lang_asset_device_info: '设备信息',
  lang_asset_realtime_data: '实时数据',
  lang_asset_basic_info: '基本信息',
  lang_asset_parameters: '设备参数',
  lang_asset_file: '设备文件',
  lang_asset_name: '设备名称',
  lang_asset_code: '设备编码',
  lang_asset_location: '位置',
  lang_asset_inventory: '盘点记录',
  lang_asset_tickets: '运维记录',

  lang_alarm_tab: '报警管理',
  lang_alarm_type_bu: '业务报警',
  lang_alarm_type_comm: '通讯报警',

  lang_alarm_filter: '筛选',
  lang_alarm_filter_level: '报警级别',
  lang_alarm_filter_type: '报警类别',
  lang_alarm_filter_time: '报警时间',

  lang_alarm_filter_type_tx1: '设备离线',
  lang_alarm_filter_type_tx2: '网关离线',
  lang_alarm_filter_type_tx3: '南向Agent离线',
  lang_alarm_filter_type_tx4: '就地系统离线',
  lang_alarm_filter_level_h: '高级',
  lang_alarm_filter_level_m: '中级',
  lang_alarm_filter_level_l: '低级',
  lang_alarm_filter_reset: '重置',
  lang_alarm_filter_start_time: '开始时间',
  lang_alarm_filter_end_time: '结束时间',
  lang_alarm_time_picker_title: '选择日期',
  lang_alarm_time_picker_ok: '确定',
  lang_alarm_time_picker_resolve: '解除',
  lang_alarm_time_picker_cancel: '取消',
  lang_alarm_time_picker_invalid_lip: '开始时间不能晚于结束时间',

  lang_alarm_tip1: '报警已解除',
  lang_alarm_tip2: '报警可能已被其他用户解除或已自动解除',
  lang_alarm_tip3: '确定解除该报警',
  lang_alarm_device: '设备',

  lang_alarm_level_h: '高',
  lang_alarm_level_m: '中',
  lang_alarm_level_l: '低',
  lang_alarm_detail: '报警详情',
  lang_alarm_list_undone: '未解除',
  lang_alarm_list_done: '已解除',
  lang_alarm_action_create_ticket: '创建工单',
  lang_alarm_action_inspect_ticket: '查看工单',
  lang_alarm_action_relieve: '解除报警',
  lang_alarm_relieve_info: '手动解除报警',
  lang_alarm_relieve_info2: '现场数据已正常，报警自动解除',
  lang_alarm_relieve_info3: '手动解除',

  lang_alarm_alert_info: '设备不在台账层级树上或没有设备台账权限',

  lang_alarm_info_step: '发生报警',
  lang_alarm_info_device: '所属设备',
  lang_alarm_info_set_value: '设定值',
  lang_alarm_info_location: '位置',
  lang_alarm_info_duration: '持续时长',
  lang_alarm_info_gateway: '所属网关',
  lang_alarm_info_create_time: '发生时间',

  lang_alarm_time_format_year: '年',
  lang_alarm_time_format_month: '月',
  lang_alarm_time_format_day: '天',
  lang_alarm_time_format_hour: '小时',
  lang_alarm_time_format_minute: '分',
  lang_alarm_time_format_second: '秒',

  lang_profile_new_version: '发现新版本',
  lang_profile_action_update: '去更新',
  lang_profile_my: '个人中心',
  lang_profile_logout: '退出登录',
  lang_profile_alert_logout: '退出',
  lang_profile_alert_info: '您要退出这个账号吗？',
  lang_profile_no_download_config: '没有配置APP的下载地址，请联系您的管理员',
  lang_profile_account: '登录用户名',
  lang_profile_display_name: '显示名称',
  lang_profile_my_partner: '我的租户',
  lang_profile_version: '版本号',
  lang_profile_alert_done: '好',
  lang_profile_updated: '当前已是最新版本',
  lang_profile_alert_do_update: '去更新',
  lang_profile_new_version_tip: '请更新至EnergyHub V${0}，马上体验！',

  lang_host_config_network_invalid: '验证失败，请检测手机网络及核对服务器地址',
  lang_host_input_server_hint: '请填写服务器地址',
  lang_host_server_config: '服务器地址配置',
  lang_host_server_example: '请输入格式为：http://192.168.1.1:8080 的服务器地址',
  lang_host_config_done: '完成',

  lang_login_title: '用户登录',
  lang_login_user_hint: '请输入您的账号',
  lang_login_password_hint: '请输入密码',
  lang_login_button: '登录',
  lang_login_remember: '保存登录名，方便下次登录',
  lang_login_help: '登录过程中遇到问题，请联系  010—8888 8888',
  lang_login_server_config: '服务器地址配置>',

  lang_create_alarm_ticket_title: '创建报警工单',
  lang_create_alarm_ticket_asset_range: '资产范围',
  lang_create_alarm_ticket_system_category: '系统分类',
  lang_create_alarm_ticket_system_category_title: '请选择系统分类',
  lang_ticket_all_categories: ['空调', '供热', '照明', '办公', '电梯', '变配电', '数据机房', '生产', '水处理', '压缩空气', '给排水', '其他', '环境参数',],
  lang_create_alarm_ticket_executor: '执行人',
  lang_create_alarm_ticket_customer: '客户',
  lang_create_alarm_ticket_Save: '保存',
  lang_create_alarm_ticket_select_executor: '请添加执行人',
  lang_create_alarm_ticket_select: '请选择',

  lang_unknown_error: '未知错误',
  lang_network_error: '加载失败，请检查您的网络设置',
  lang_cookie_invalid: '登录失效，请重新登录',
  lang_permission_expired: '您的功能权限已失效',
  lang_account_deleted: '您的帐户已被删除，请联系您的管理员',
  lang_server_error: '系统正在升级，马上变身回来',
  lang_exit_app: '再按一次退出应用',
  lang_camera_permission: '请在手机的"设置"中，允许此应用访问您的摄像头',
  lang_scan_page_light: '手电筒',
  lang_scan_page_light_on: '打开',
  lang_scan_page_light_off: '关闭',

  lang_login_error_not_exist_account: '您输入的用户名不是系统注册用户',
  lang_login_error_invalid_account: '您输入的用户名或密码错误',

  lang_toolbar_ok: '完成',
  lang_toolbar_submit: '提交',

  lang_image_picker_cancel: '取消',
  lang_image_picker_accept: '允许',
  lang_image_picker_accept_msg: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的摄像头',
  lang_image_picker_access_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用读写您的存储空间',
  lang_image_picker_open_photos: '打开照相机',
  lang_image_picker_from_photos: '从手机相册获取',
  lang_image_picker_title: '图片',
  lang_image_picker_access_photos: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的相册',
  lang_image_picker_read_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的存储',
  lang_image_picker_no_photos: '暂无图片',
  lang_image_take_photo: '拍照',

  lang_offline_view_tip: '无网络，点击重试！',

  lang_ticket_select_site: '请选择位置',
  lang_ticket_select_asset_range: '请选择资产范围',
  lang_ticket_title_create: '创建工单',
  lang_ticket_title_edit: '编辑工单',
  lang_ticket_valid_select_assets: '请选择资产范围',
  lang_ticket_valid_select_time: '请填写预计耗时',
  lang_ticket_valid_title: '请添加工单名称',
  lang_ticket_valid_content: '请添加任务描述',
  lang_ticket_valid_use_time: '请输入预计耗时',
  lang_ticket_valid_use_time_format: '预计耗时输入不合法',
  lang_ticket_create_start_time: '建议执行时间',
  lang_ticket_create_duration: '预计耗时',
  lang_ticket_create_duration_hint: '请输入',
  lang_ticket_create_duration_units: ['小时', '天'],
  lang_ticket_create_success_tip: '工单创建成功',
  lang_ticket_delete_tip: '确定要删除工单吗?',

  lang_ticket_edit_title_tip: '标题最多30个字',
  lang_ticket_edit_title_tip2: '请添加工单名称',
  lang_ticket_edit_content_tip: '请详细描述工单任务',

  lang_select_partners: '选择租户',
};
