source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Rock' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'

  pod 'react-native-open-file', :path => '../node_modules/react-native-open-file'
  pod 'react-native-file-opener', :path => '../node_modules/react-native-file-opener'
  pod 'react-native-pinch', :path => '../node_modules/react-native-pinch'
  pod 'react-native-screenshot-detector', :path => '../node_modules/react-native-screenshot-detector'
  pod '@remobile_react-native-toast', :path => '../node_modules/@remobile/react-native-toast'
  pod 'react-native-detect-new-photo', :path => '../node_modules/react-native-detect-new-photo'
  #pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  #pod 'SensorsAnalyticsSDK', '3.1.6'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
  end

end
